target-version = "py313"
line-length = 88
select = ["E", "F", "I", "N", "W", "B", "C4", "SIM", "ARG", "PL", "RUF"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[isort]
known-first-party = ["scraper"]
