version: '3'

vars:
  PYTHON: python3
  DOCKER_COMPOSE: docker-compose

includes:
  code_scout:
    taskfile: ./code_scout/Taskfile.yml
    dir: ./code_scout

tasks:
  install:
    desc: Install dependencies
    cmds:
      - task: code_scout:install
  
  lock:
    desc: Update lock files
    cmds:
      - task: code_scout:lock
  
  format:
    desc: Format code with ruff
    cmds:
      - task: code_scout:format
  
  lint:
    desc: Lint code with ruff and pyright
    cmds:
      - task: code_scout:lint
  
  test:
    desc: Run tests
    cmds:
      - task: code_scout:test
