version: '3'

vars:
  PYTHON: python3

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pwd
      - poetry install

  lock:
    desc: Update lock file
    cmds:
      - poetry lock

  format:
    desc: Format code with ruff
    cmds:
      - poetry run ruff format .

  lint:
    desc: Lint code with ruff and basedpyright
    cmds:
      - poetry run ruff check --fix .
      - poetry run ruff check .
      - basedpyright

  ci:
    desc: Run CI checks
    cmds:
      - task: format
      - task: lint
      - task: test

  test:
    desc: Run tests
    cmds:
      - poetry run pytest
