version: '3'

vars:
  PYTHON: python3

tasks:
  install:
    desc: Install dependencies
    cmds:
      - pwd
      - poetry install

  lock:
    desc: Update lock file
    cmds:
      - poetry lock

  format:
    desc: Format code with ruff
    cmds:
      - poetry run ruff format .

  lint:
    desc: Lint code with ruff and mypy
    cmds:
      - poetry run ruff check .
      - poetry run mypy .

  test:
    desc: Run tests
    cmds:
      - poetry run pytest
